"""Population module events.

Phase 12e event types published by population subsystem engines.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

from stochastic_warfare.core.events import Event
from stochastic_warfare.core.types import ModuleId, Position


@dataclass(frozen=True)
class DisplacementEvent(Event):
    """Civilians displaced from a region."""

    timestamp: datetime
    source: ModuleId
    region_id: str
    displaced_count: int
    destination_region_id: str | None = None


@dataclass(frozen=True)
class CollateralDamageEvent(Event):
    """Civilian casualties from military action."""

    timestamp: datetime
    source: ModuleId
    position: Position
    casualties: int
    cause: str  # "indirect_fire", "air_strike", "ground_combat"
    responsible_side: str


@dataclass(frozen=True)
class DispositionChangeEvent(Event):
    """Civilian disposition changed in a region."""

    timestamp: datetime
    source: ModuleId
    region_id: str
    old_disposition: str
    new_disposition: str


@dataclass(frozen=True)
class HumintTipEvent(Event):
    """HUMINT tip generated by civilian population."""

    timestamp: datetime
    source: ModuleId
    region_id: str
    target_unit_id: str
    reported_position: Position
    reliability: float  # 0.0-1.0
    delay_hours: float
    tip_side: str  # which side receives the tip
